<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function llom_h5p_logging_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the esn_cas_attributes module.
    case 'help.page.llom_h5p_logging':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('LLOM score reporting for the H5P question type') . '</p>';
      return $output;

    default:
  }
}
