#!/bin/bash

# Install a Drupal site from .env
echo -e "\nInstall Drupal from environment variables."

# Check for a local drush binary
DRUSH="vendor/bin/drush"
if [[ -f $PWD/${DRUSH} ]]; then
  echo -e ">> Drush found:  "$PWD/${DRUSH}
else
  echo -e ">> Drush is missing! Exiting..."
  exit 1
fi

# Check for .env in the current directory
ENV=".env"
if [[ -f $PWD/${ENV} ]]; then
  echo -e ">> .env found:   "$PWD/${ENV}
  source ${ENV}
else
  echo -e ">> .env is missing! Exiting..."
  exit 1
fi

# Show .env variables
echo -e "\nDatabase settings"
echo "DB_NAME:      "${DB_NAME}
echo "DB_USER:      "${DB_USER}
echo "DB_PASSWORD:  "${DB_PASSWORD}
echo "DB_HOST:      "${DB_HOST}
echo "DB_PORT:      "${DB_PORT}
echo "DB_DRIVER:    "${DB_DRIVER}
echo -e "\nSite settings"
echo "PROFILE:      "${PROFILE}
echo "SITE_NAME:    "${SITE_NAME}
echo "SITE_MAIL:    "${SITE_MAIL}
echo "ACCOUNT_NAME: "${ACCOUNT_NAME}
echo "ACCOUNT_MAIL: "${ACCOUNT_MAIL}
if [[ ${ACCOUNT_PASS} == "" ]]; then
  echo -e "ACCOUNT_PASS: \033[1mgenerated by Drush\033[0m"
else
  echo "ACCOUNT_PASS: "${ACCOUNT_PASS}
fi

# Prompt to proceed
echo
while true; do
    read -p "Do you wish to install the site? [Y/N] " yn
    case $yn in
        [Yy]* ) echo -e "\nPerforming the installation..."; break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Perform the site install
${DRUSH} site-install ${PROFILE} \
install_configure_form.enable_update_status_emails=NULL \
--db-url="${DB_DRIVER}"://"${DB_USER}":"${DB_PASSWORD}"@"${DB_HOST}":\
"${DB_PORT}"/"${DB_NAME}" \
--account-name="${ACCOUNT_NAME}" \
--account-mail="${ACCOUNT_MAIL}" \
--site-mail="${SITE_MAIL}" \
--account-pass="${ACCOUNT_PASS}" \
--site-name="${SITE_NAME}"

# Correct permissions to avoid future issues
echo -e "\nCorrecting permissions..."
chmod 0755 $PWD/web/sites/default
echo -e "Added write permission to web/sites/default"
chmod 0644 $PWD/web/sites/default/settings.php
echo -e "Added write permission to web/sites/default/settings.php"
chmod 0644 $PWD/web/sites/default/settings.local.php
echo -e "Added write permission to web/sites/default/settings.local.php"

echo -e "\nFind the site at http://${PROJECT_BASE_URL}:${HTTP_PORT}"
exit 0
