#!/bin/bash

# Install a Drupal site from .env
echo -e "\nInstall Drupal from existing configuration."

# Check for a local drush binary
DRUSH="vendor/bin/drush"
if [[ -f $PWD/${DRUSH} ]]; then
  echo -e ">> Drush found:         "$PWD/${DRUSH}
else
  echo -e ">> Drush is missing! Exiting..."
  exit 1
fi

# Check for .env in the current directory
ENV=".env"
if [[ -f $PWD/${ENV} ]]; then
  echo -e ">> .env found:          "$PWD/${ENV}
  source ${ENV}
else
  echo -e ">> .env is missing! Exiting..."
  exit 1
fi

# Check for .yml files in the config/sync directory
EXTENSION_YML="config/sync/core.extension.yml"
if [[ -f $PWD/${EXTENSION_YML} ]]; then
  echo -e ">> Configuration found: "$PWD/${EXTENSION_YML}
else
  echo -e ">> Configuration is missing! Exiting..."
  exit 1
fi

# Check for existing local settings file in web/sites/default
SETTINGS_LOCAL="web/sites/default/settings.local.php"
if [[ -f $PWD/${SETTINGS_LOCAL} ]]; then
  echo -e ">> settings.local.php found: "$PWD/${SETTINGS_LOCAL}
else
  echo -e ">> settings.local.php is missing! Run composer install and try again"
  exit 1
fi

# Show .env variables
echo -e "\nDatabase settings"
echo "DB_NAME:      "${DB_NAME}
echo "DB_USER:      "${DB_USER}
echo "DB_PASSWORD:  "${DB_PASSWORD}
echo "DB_HOST:      "${DB_HOST}
echo "DB_PORT:      "${DB_PORT}
echo "DB_DRIVER:    "${DB_DRIVER}
echo -e "\nSite settings"
echo -e "PROFILE:      \033[9m"${PROFILE}"\033[0m \033[1mminimal\033[0m"
echo "SITE_NAME:    "${SITE_NAME}
echo "SITE_MAIL:    "${SITE_MAIL}
echo "ACCOUNT_NAME: "${ACCOUNT_NAME}
echo "ACCOUNT_MAIL: "${ACCOUNT_MAIL}
if [[ ${ACCOUNT_PASS} == "" ]]; then
  echo -e "ACCOUNT_PASS: \033[1mgenerated by Drush\033[0m"
else
  echo "ACCOUNT_PASS: "${ACCOUNT_PASS}
fi

# Prompt to proceed
echo
while true; do
    read -p "Do you wish to install the site? [Y/N] " yn
    case $yn in
        [Yy]* ) echo -e "\nPerforming the installation..."; break;;
        [Nn]* ) exit 0;;
        * ) echo "Please answer yes or no.";;
    esac
done

# Change the configuration files to allow the config install
if [[ ${PROFILE} != "minimal" ]]; then
  OLDMODULE=${PROFILE}": 1000"
  NEWMODULE="minimal: 1000"
  sed -i "s/${OLDMODULE}/${NEWMODULE}/g" $PWD/${EXTENSION_YML}
  OLDPROFILE="profile: "${PROFILE}
  NEWPROFILE="profile: minimal"
  sed -i "s/${OLDPROFILE}/${NEWPROFILE}/g" $PWD/${EXTENSION_YML}
fi

# Perform the site install
${DRUSH} site-install minimal --existing-config \
install_configure_form.enable_update_status_emails=NULL \
--db-url="${DB_DRIVER}"://"${DB_USER}":"${DB_PASSWORD}"@"${DB_HOST}":\
"${DB_PORT}"/"${DB_NAME}" \
--account-name="${ACCOUNT_NAME}" \
--account-mail="${ACCOUNT_MAIL}" \
--site-mail="${SITE_MAIL}" \
--account-pass="${ACCOUNT_PASS}" \
--site-name="${SITE_NAME}"

# Correct permissions to avoid future issues
echo -e "\nCorrecting permissions..."
chmod 0755 $PWD/web/sites/default
echo -e "Added write permission to web/sites/default"
chmod 0644 $PWD/web/sites/default/settings.php
echo -e "Added write permission to web/sites/default/settings.php"
chmod 0644 $PWD/web/sites/default/settings.local.php
echo -e "Added write permission to web/sites/default/settings.local.php"

echo -e "\nFind the site at http://${PROJECT_BASE_URL}:${HTTP_PORT}"
exit 0
