<?php

/**
 * @file
 * Contains llom_h5p_content.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function llom_h5p_content_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the llom_h5p_content module.
    case 'help.page.llom_h5p_content':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('LLOM H5P Content') . '</p>';
      return $output;

    default:
  }
}
